pmarlen-web-ligth/src/main/java/com/pmarlen/jsf/ClienteMB.java
package com.pmarlen.jsf;

import com.pmarlen.backend.dao.ClienteDAO;
import com.pmarlen.backend.dao.DAOException;
import com.pmarlen.backend.model.Cliente;
import com.pmarlen.backend.model.quickviews.ClienteQuickView;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import org.primefaces.event.SelectEvent;

@ManagedBean(name="clienteMB")
@SessionScoped
public class ClienteMB implements Serializable {
	private transient final Logger logger = Logger.getLogger(ClienteMB.class.getSimpleName());
	List<ClienteQuickView> entityList;
	Integer viewRows;
	ClienteQuickView selectedEntity;
	String dialogTitle;
	
	@PostConstruct
    public void init() {
		logger.trace("ClienteMB: init.");
        try{
			entityList = ClienteDAO.getInstance().findAll();
		}catch(DAOException de){
			logger.error(de.getMessage());
			entityList = new ArrayList<ClienteQuickView>();
		}
		logger.trace("ClienteMB: init:entityList="+entityList);
		viewRows = 10;
		dialogTitle ="DATOS DEL CLIENTE";
    }
	
	public String reset() {
		logger.trace("ClienteMB: rest.");
        init();
		return "/pages/cliente";
    }

	public String getDialogTitle() {
		return dialogTitle;
	}
	
	
	
	public void selectEntity(ActionEvent event){
		logger.trace("ClienteMB: selectCliente.");
	}
	
	public void actionX(ActionEvent event){
		logger.trace("ClienteMB: actionX.");
	}
	
	public void prepareForNew() {
		logger.trace("ClienteMB prepareForNew");
		//dialogTitle ="AGREGAR NUEVO CLIETE";
		this.selectedEntity = new ClienteQuickView();
        this.selectedEntity.setId(null);
	}
	
	public void setSelectedEntity(ClienteQuickView selectedCliente) {
		logger.trace("ClienteMB setSelectedCliente.id="+selectedCliente.getId());
		//dialogTitle ="INFORMACIÓN DEL CLEINTE";
		this.selectedEntity = selectedCliente;
		if(this.selectedEntity.getDireccionFacturacion()== null){
			this.selectedEntity.setDireccionFacturacion(this.selectedEntity.getDireccion());
		}
	}
	
	public void save(){
		logger.trace("ClienteMB: saveSelectedCliente:id:"+selectedEntity.getId());
		
		try{
//			if(selectedEntity.getTelefonos().contains("0000")){
//				throw new Exception("Telephone 0000 not allowed.");
//			}
			int u=-1;			
			if(selectedEntity.getId()==null){
				u=ClienteDAO.getInstance().insert(selectedEntity);			
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, dialogTitle, "SE CREÓ CORRECTAMENTE NUEVO CLIENTE"));			
			} else{
				u=ClienteDAO.getInstance().update(selectedEntity);
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, dialogTitle, "SE ACTUALIZARÓN CORRECTAMENTE LOS DATOS DEL CLIENTE"));			
			}
			reset();
		} catch(Exception e){
			logger.error("AL GUARDAR CLIENTE:",e);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, dialogTitle, "OCURRIO UN ERROR AL GUARDAR"));
			FacesContext.getCurrentInstance().validationFailed();
		}
		
	}

	public Cliente getSelectedEntity() {
		return selectedEntity;
	}
	
    public void onEntityChosen(SelectEvent event) {
        Integer entityId = (Integer) event.getObject();
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Entity Selected", "Id:" + entityId);
         
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
	public List<ClienteQuickView> getEntityList() {
		return entityList;
	}
	
	public int getSizeList(){
		return entityList.size();
	}
	
	public void setViewRows(Integer viewRows) {
		this.viewRows = viewRows;
	}

	public Integer getViewRows() {
		return viewRows;
	}
}

pmarlen-web-ligth/src/main/java/com/pmarlen/jsf/VentasSucursalesMB.java
package com.pmarlen.jsf;

import com.pmarlen.backend.dao.DAOException;
import com.pmarlen.backend.dao.SucursalDAO;
import com.pmarlen.backend.model.Sucursal;
import com.pmarlen.jsf.model.EntradaSalidaLazyDataModel;
import com.pmarlen.model.Constants;
import java.io.Serializable;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.model.SelectItem;
import org.apache.log4j.Logger;

@ManagedBean(name="ventasSucursalesMB")
@ViewScoped

public class VentasSucursalesMB implements Serializable {
	private transient static Logger logger = Logger.getLogger(VentasSucursalesMB.class.getSimpleName());
	private int		sucursalId = -1;
	private int		caja       = 0;
	private ArrayList<SelectItem> sucursalesList;
	private ArrayList<SelectItem> cajasList;

	class IntervaloFecha implements Serializable{
		Date fechaInicial;
		Date fechaFinal;
		IntervaloFecha(Date fi,Date ff){
			fechaInicial =  fi;
			fechaFinal   =  ff;
		}
	}
	
	
	static final String IF_SOLO_YEAR = "ESTE AÑO";
	static final String IF_SPEC = "ESPECIFICO";
	static final String IF_SOLO_MES = "ESTE MES";
	static final String IF_SOLO_SEMANA = "ESTA SEMANA";
	static final String IF_SOLO_HOY = "SOLO HOY";

	private String intFechaSelec=IF_SOLO_HOY;	
	
	private ArrayList<SelectItem> intervalosFechas;
	private LinkedHashMap<String,IntervaloFecha> intervalosFechasList;
	private Date fechaInicial;
	private Date fechaFinal;
	private Double totalVenta;
	private static final long day  = 86400000;
	private static final long week = day * 7;
	private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
	@ManagedProperty(value = "#{editarPedidoVentaMB}")
	private EditarPedidoVentaMB editarPedidoVentaMB;	
	
	private EntradaSalidaLazyDataModel lazyModel;	
	private int viewRows;
	
	@PostConstruct
	public void init(){		
		logger.debug("init:");
		intFechaSelec = IF_SOLO_HOY;
		especificarFecha  = false;
		totalVenta = 0.0;
		getIntervalosFechas();
		onIntervaloFechaChange();
		getSucursalesList();		
		viewRows = 25;
	}

	public void refrescar(){
		fechaFinal = new Timestamp(fechaFinal.getTime()+day-1);
		logger.debug("refrescar: fechas ["+fechaInicial+","+fechaFinal+"]");
		lazyModel = null;
	}

	public void onSucursalChange() {
		logger.debug("onSucursalChange:sucursalId="+sucursalId);
		lazyModel = null;
	}
	
	public void onCajaChange() {
		logger.debug("onCajaChange:caja="+caja);
		lazyModel = null;
	}

	public void setEditarPedidoVentaMB(EditarPedidoVentaMB editarPedidoVentaMB) {
		this.editarPedidoVentaMB = editarPedidoVentaMB;
	}
	
	public void editar(int id){
		logger.trace("editar:id="+id);
		editarPedidoVentaMB.editar(id);
	}
	public String editarPedidoAction(int pedidoVentaId){
		logger.trace("editarPedidoAction:pedidoVentaId="+pedidoVentaId);
		return editarPedidoVentaMB.editar(pedidoVentaId);
	}
		
	public int getSizeList(){
		logger.trace("getSizeList()");
		return lazyModel.getRowCount();
	}

	public int getViewRows() {
		logger.trace("getViewRows()");
		return viewRows;
	}

	public void setViewRows(int viewRows) {
		logger.trace("setViewRows("+viewRows+")");
		this.viewRows = viewRows;
	}

	public String getImporteMoneda(double f){
		return Constants.getImporteMoneda(f);
	}

	public EntradaSalidaLazyDataModel getLazyModel() {
		if(lazyModel == null) {
			logger.info("getLazyModel:sucursalId="+sucursalId+", caja="+caja);
			lazyModel = new EntradaSalidaLazyDataModel(Constants.TIPO_MOV_SALIDA_ALMACEN_VENTA,sucursalId,caja, true,
					new Timestamp(fechaInicial.getTime()),new Timestamp(fechaFinal.getTime()));
		}
		return lazyModel;
	}
	
	public double getTotalVenta(){
		return lazyModel.getTotalVenta();
	}
	
	public void setSucursalId(int sucursalId) {
		this.sucursalId = sucursalId;
	}

	public int getSucursalId() {
		return sucursalId;
	}
	
	public ArrayList<SelectItem> getIntervalosFechas() {
		if(intervalosFechas == null){
			intervalosFechas = new ArrayList<SelectItem>();
			intervalosFechasList = new LinkedHashMap<String,IntervaloFecha> ();
			Date today = new Date();
			Date xd = null;
			try{
				xd = sdf.parse(sdf.format(today));
			}catch(ParseException e){
			}
			Calendar cal = Calendar.getInstance();
			cal.setTime(xd);
			//	D L M M J V S
			//	1 2 3 4 5 6 7		
			int dow = cal.get(Calendar.DAY_OF_WEEK);
			int dom = cal.get(Calendar.DAY_OF_MONTH) - 2 ;
			int doy = cal.get(Calendar.DAY_OF_YEAR)  - 2;
			
			int dbw = 0;
			if(dow == 1) {
				dbw = 7;
			} else {
				dbw = dow - 1;
			}
			Date fechaInicialInt = null;
			Date fechaFinalInt   = null;
			IntervaloFecha intFec = null;
			
			
			fechaInicialInt = new Timestamp(xd.getTime()          );
			fechaFinalInt   = new Timestamp(xd.getTime() + day - 1);			
			intFec = new IntervaloFecha(fechaInicialInt,fechaFinalInt);
			intervalosFechasList.put(IF_SOLO_HOY,intFec);
			intervalosFechas.add(new SelectItem(IF_SOLO_HOY, IF_SOLO_HOY));
			
			fechaInicialInt = new Timestamp(xd.getTime() - dbw * day);
			fechaFinalInt   = new Timestamp(xd.getTime() + day - 1  );						
			intFec = new IntervaloFecha(fechaInicialInt,fechaFinalInt);			
			intervalosFechasList.put(IF_SOLO_SEMANA,intFec);
			intervalosFechas.add(new SelectItem(IF_SOLO_SEMANA, IF_SOLO_SEMANA));
			
			fechaInicialInt = new Timestamp(xd.getTime() - dom * day);
			fechaFinalInt   = new Timestamp(xd.getTime() + day - 1  );			
			intFec = new IntervaloFecha(fechaInicialInt,fechaFinalInt);			
			intervalosFechasList.put(IF_SOLO_MES,intFec);
			intervalosFechas.add(new SelectItem(IF_SOLO_MES, IF_SOLO_MES));
			
			fechaInicialInt = new Timestamp(xd.getTime() - doy * day);
			fechaFinalInt   = new Timestamp(xd.getTime() + day - 1  );			
			intFec = new IntervaloFecha(fechaInicialInt,fechaFinalInt);			
			intervalosFechasList.put(IF_SOLO_YEAR,intFec);
			intervalosFechas.add(new SelectItem(IF_SOLO_YEAR, IF_SOLO_YEAR));
			
			fechaInicialInt = new Timestamp(xd.getTime()          );
			fechaFinalInt   = new Timestamp(xd.getTime() + day - 1);			
			intFec = new IntervaloFecha(fechaInicialInt,fechaFinalInt);			
			intervalosFechasList.put(IF_SPEC,intFec);			
			intervalosFechas.add(new SelectItem(IF_SPEC, IF_SPEC));
		}
		return intervalosFechas;
	}
	
	private boolean especificarFecha;
	
	public void onIntervaloFechaChange() {		
		logger.debug("onIntervaloFechaChange:intFechaSelec="+intFechaSelec);
		if(intFechaSelec.endsWith(IF_SPEC)) {
			especificarFecha  = true;
			IntervaloFecha ifs = intervalosFechasList.get(intFechaSelec);
			fechaInicial = ifs.fechaInicial;
			fechaFinal   = ifs.fechaFinal;
			logger.debug("\t-->onIntervaloFechaChange: SECIFICAR: fechaInicial="+fechaInicial+", fechaFinal="+fechaFinal);
		} else {
			especificarFecha  = false;
			IntervaloFecha ifs = intervalosFechasList.get(intFechaSelec);
			fechaInicial = ifs.fechaInicial;
			fechaFinal   = ifs.fechaFinal;
			logger.debug("\t-->onIntervaloFechaChange:INTERVALO:fechaInicial="+fechaInicial+", fechaFinal="+fechaFinal);
			lazyModel = null;
		}
	}
	
	public ArrayList<SelectItem> getSucursalesList() {
		if(sucursalesList==null){
			sucursalesList = new ArrayList<SelectItem>();
			List<Sucursal> sucursales=null;
			try {
				sucursales=(List<Sucursal>) SucursalDAO.getInstance().findAll();
			}catch(DAOException de){
				logger.error(de.getMessage());			
			}
			
			if(sucursales != null){				
				for(Sucursal s:sucursales){
					if(s.getIdPadre() != null){						
						sucursalesList.add(new SelectItem(s.getId(),s.getNombre()));			
					}
				}
				sucursalId = (Integer)sucursalesList.get(0).getValue();
			}
		}
		return sucursalesList;
	}

	public ArrayList<SelectItem> getCajasList() {
		if(cajasList==null){
			cajasList = new ArrayList<SelectItem>();
				
			cajasList.add(new SelectItem(0,"[TODAS LAS CAJAS ]"));
			cajasList.add(new SelectItem(1 ,"[---- CAJA 1 ----]"));
			cajasList.add(new SelectItem(2 ,"[---- CAJA 2 ----]"));
			cajasList.add(new SelectItem(3 ,"[---- CAJA 3 ----]"));
			cajasList.add(new SelectItem(4 ,"[---- CAJA 4 ----]"));
		}
		return cajasList;
	}
	
	/**
	 * @return the fechaInicial
	 */
	public Date getFechaInicial() {
		return fechaInicial;
	}

	/**
	 * @param fechaInicial the fechaInicial to set
	 */
	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	/**
	 * @return the fechaFinal
	 */
	public Date getFechaFinal() {
		return fechaFinal;
	}

	/**
	 * @param fechaFinal the fechaFinal to set
	 */
	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}
	/**
	 * @return the intFechaSelec
	 */
	public String getIntFechaSelec() {
		return intFechaSelec;
	}

	/**
	 * @param intFechaSelec the intFechaSelec to set
	 */
	public void setIntFechaSelec(String intFechaSelec) {
		this.intFechaSelec = intFechaSelec;
	}

	/**
	 * @return the especificarFecha
	 */
	public boolean isEspecificarFecha() {
		return especificarFecha;
	}

	/**
	 * @param especificarFecha the especificarFecha to set
	 */
	public void setEspecificarFecha(boolean especificarFecha) {
		this.especificarFecha = especificarFecha;
	}
	
	public boolean isIntervaloEspecifico() {
		return intFechaSelec.equals(IF_SPEC);
	}

	public int getCaja() {
		return caja;
	}

	public void setCaja(int caja) {
		this.caja = caja;
	}
	
}

pmarlen-web-ligth/src/main/webapp/pages/mensajeBroadcast.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/mainWithMenu.xhtml">

    <ui:define name="title">
        PM > INICIO
    </ui:define>

    <ui:define name="body-title">
        <h:outputText value="Mensaje a todos los usuarios."/>
    </ui:define>

    <ui:define name="body">
		<h:form id="formHome">
			<h:panelGrid columns="2" columnClasses="">
				<h:panelGroup>
					<h:graphicImage value="/images/msg_message.png"/>
				</h:panelGroup>

				<h:panelGroup>
                    <h:panelGrid columns="4" cellpadding="2">
                        <h:outputLabel for="xvalue" value="Mesaje Global :" />
                        <p:inputText id="xvalue" value="#{systemInfoMB.systemWallMessage}"/>
                    </h:panelGrid>
				</h:panelGroup>

			</h:panelGrid>

		</h:form>		
    </ui:define>

</ui:composition>

pmarlen-web-ligth/src/main/webapp/pages/ventasSucursales.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/mainWithMenu.xhtml">

    <ui:define name="title">
        PEDIDOS DE VENTA SUCURSALES
    </ui:define>

    <ui:define name="body-title">
        VENTA EN SUCURSALES
    </ui:define>

    <ui:define name="body">		

		<h:form id="form1" rendered="true">

			<h:panelGrid columns="1" cellpadding="0" id="panel3" columnClasses="leftAlign" width="100%" >						
				<h:panelGrid columns="2" cellpadding="0" width="100%" columnClasses="columnWidth20 rightAlign, columnWidth80 leftAlign,columnWidth20 rightAlign, columnWidth80 leftAlign">
					<p:outputLabel for="sucursal" value="SUCURSAL / CAJA:" />
					<h:panelGroup>
						<p:selectOneMenu id="sucursal" value="#{ventasSucursalesMB.sucursalId}" >				
							<f:selectItems  value="#{ventasSucursalesMB.sucursalesList}"/>					
							<p:ajax listener="#{ventasSucursalesMB.onSucursalChange}" process=":form1:sucursal" update=":form1:"/>
						</p:selectOneMenu>
						
						<p:selectOneMenu id="caja" value="#{ventasSucursalesMB.caja}" >				
							<f:selectItems  value="#{ventasSucursalesMB.cajasList}"/>					
							<p:ajax listener="#{ventasSucursalesMB.onCajaChange}" process=":form1:caja" update=":form1:"/>
						</p:selectOneMenu>
						
					</h:panelGroup>
					<p:outputLabel for="intervaloFec" value="INTERVALO DE FECHA :" />
					
					<h:panelGroup id="fechas" styleClass="alignTop">
						<p:selectOneMenu id="intervaloFec" value="#{ventasSucursalesMB.intFechaSelec}" >				
							<f:selectItems  value="#{ventasSucursalesMB.intervalosFechas}"/>					
							<p:ajax listener="#{ventasSucursalesMB.onIntervaloFechaChange}" process=":form1:intervaloFec" update=":form1:"/>
						</p:selectOneMenu>
						<p:spacer width="5"/>
						<h:outputLabel value=" DESDE : " for="fechaInicial" />
						<p:calendar id="fechaInicial" value="#{ventasSucursalesMB.fechaInicial}" showOn="button" pattern="yyyy/MM/dd" locale="es" lang="es" size="10" disabled="#{not ventasSucursalesMB.intervaloEspecifico}"/>						
						<h:outputLabel value=" HASTA : " for="fechaFinal" />
						<p:calendar id="fechaFinal"   value="#{ventasSucursalesMB.fechaFinal}" showOn="button"   pattern="yyyy/MM/dd" locale="es" lang="es" size="10" disabled="#{not ventasSucursalesMB.intervaloEspecifico}"/>
					</h:panelGroup>
					
				</h:panelGrid>

				<p:dataTable  var="pv" value="#{ventasSucursalesMB.lazyModel}"
							  paginator="true" lazy="true"
							  id="pvTable" emptyMessage="-- SIN ELEMENTOS --" 							  
							  rows="#{ventasSucursalesMB.viewRows}"
							  paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} [#{ventasSucursalesMB.sizeList}]"
							  rowsPerPageTemplate="10,25,100">
					<f:facet name="header">
						OPCIONES :								
						<p:commandButton value="RECARGAR" actionListener="#{ventasSucursalesMB.refrescar}" update=":form1" icon="ui-icon-arrowrefresh-1-s"/>
						<p:spacer width="100" height="10"/>
						<h:commandLink>
							<p:graphicImage value="/images/excel_file.png" width="16"/>
							<p:dataExporter type="xls" target="pvTable" fileName="VentasSucursales" />
						</h:commandLink>
						<p:spacer width="30" height="10"/>
						<h:commandLink>
							<p:graphicImage value="/images/pdf_file.png" width="16"/>
							<p:dataExporter type="pdf" target="pvTable" fileName="VentasSucursales" />
						</h:commandLink>
					</f:facet>
					
					<p:column headerText="#" width="10%" filterBy="#{pv.id}" filterMatchMode="contains" filterStyle="width:30px;" >
						<p:panelGrid columns="1" columnClasses="centerAlign" >		
							<!--
							<p:commandButton actionListener="#{ventasSucursalesMB.editar(pv.id)}" value="#{pv.id}" onsuccess="edit();"/>
							-->
							<h:outputText value="# #{pv.numeroTicket}" />
							<h:outputText value="[#{pv.id}]" />
							<h:panelGroup>
								
								<h:outputLink id="pdfLink" value="#{request.contextPath}/docs/notas/Nota_PerfumeriaMarlen_No_#{pv.id}.pdf" target="_blank">
									<h:graphicImage value="/images/nota_16x16.png" title="PDF NOTA DE VENTA ##{pv.id}"/>
								</h:outputLink>
							<!--	
								<h:outputLink id="pdfLinkNoImages" value="#{request.contextPath}/docs/notas/Nota_PerfumeriaMarlen_No_#{pv.id}_paraImprimir.pdf" target="_blank">
									<h:graphicImage value="/images/nota_16x16.png" title="PDF NOTA DE VENTA ##{pv.id} PARA IMPRIMIR HOJAS MEMBRETADAS"/>
								</h:outputLink>
							-->	
							</h:panelGroup>
						</p:panelGrid>
					</p:column>
					
					<p:column headerText="CREADO / ACTUAL" width="20%">
						<p:panelGrid columns="1" columnClasses="centerAlign" style="border: none; border-collapse: none; ">							
							<h:outputText value="CREADO / #{pv.fechaCreo} (#{pv.usuarioEmailCreo}) "/>
							<h:outputText value="#{pv.estadoDescripcion} / #{pv.estadoActualFecha} (#{pv.estadoActualUsuarioEmail}" />							
						</p:panelGrid>
						
					</p:column>
					
					<p:column headerText="DATOS" width="30%">
						<p:panelGrid columns="2" columnClasses="columnWidth30 rightAlign,columnWidth70 leftAlign">
							<h:outputText value="R.F.C. :" />
							<h:outputText value="#{pv.clienteRFC}" />
							<h:outputText value="RAZÓN SOCIAL :" />
							<h:outputText value="#{pv.clienteRazonSocial}" />
							<h:outputText value="NOMBRE ESTAB.:" />
							<h:outputText value="#{pv.clienteNombreEstablecimiento}" />							
							<h:outputText value="ELEM/ # PRODS.:" />
							<h:outputText value="#{pv.numElementos} / #{pv.totProds}" />
							<h:outputText value="FORMA DE PAGO :" />
							<h:outputText value="#{pv.formaDePagoDescripcion}" />
							<h:outputText value="METODO DE PAGO:" />
							<h:outputText value="#{pv.metodoDePagoDescripcion}" />	
							<h:outputText value="COMENTARIOS:" />
							<h:outputText value="#{pv.comentarios}" />
							<h:outputText value="CAJA:" />
							<h:outputText value="#{pv.caja}" />							
						</p:panelGrid>
					</p:column>
					
					<p:column headerText="IMPORTE - DESC." width="20%">
						<p:panelGrid columns="2" columnClasses="rightAlign,rightAlign">
							<h:outputText value="IMPORTE BRUTO :" />
							<h:outputText value="#{pv.importeBruto}" >
								<f:convertNumber maxFractionDigits="2" pattern="$ ###,###,##0.00" locale="es_MX"/>
							</h:outputText>
							
							<h:outputText value="- DESCUENTOS :" />
							<h:outputText value="#{pv.porcentajeDescuentoCalculado}% + #{pv.porcentajeDescuentoExtra}%" />
							
							<h:outputText value="TOTAL :" />
							<h:outputText value="#{pv.importeTotal}" styleClass="littleLabel_bold_right">
								<f:convertNumber maxFractionDigits="2" pattern="$ ###,###,##0.00" locale="es_MX"/>
							</h:outputText>
						</p:panelGrid>
					</p:column>

					<f:facet name="footer">
						<p:panelGrid columns="4" >
							<h:outputText value="ELEMENTOS : "  />
							<h:outputText value="#{ventasSucursalesMB.sizeList}" />
							<h:outputText value="TOTAL : "/>
							
							<h:outputText value="#{ventasSucursalesMB.totalVenta}" styleClass="littleLabel_bold_right">
								<f:convertNumber maxFractionDigits="2" pattern="$ ###,###,##0.00" locale="es_MX"/>
							</h:outputText>
						</p:panelGrid>
					</f:facet>
				</p:dataTable>

			</h:panelGrid>
			<script>
				function edit(){
					location.href = "editarPedidoVenta.jsf";
				}
				
				$(document).ready(function() {
					PrimeFaces.locales['es'] = { closeText: 'Cerrar', prevText: 'Anterior', nextText: 'Siguiente', monthNames: ['Enero','Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun','Jul','Ago','Sep','Oct','Nov','Dic'], dayNames: ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'], dayNamesShort: ['Dom','Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'], dayNamesMin: ['D','L','M','X','J','V','S'], weekHeader: 'Semana', firstDay: 1, isRTL: false, showMonthAfterYear: false, yearSuffix: '', timeOnlyTitle: 'Sólo hora', timeText: 'Tiempo', hourText: 'Hora', minuteText: 'Minuto', secondText: 'Segundo', currentText: 'Fecha actual', ampm: false, month: 'Mes', week: 'Semana', day: 'Día', allDayText : 'Todo el día' }; 
				});
			</script>		
			
		</h:form>

	</ui:define>

</ui:composition>